package com.qms.reporting;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.ByteArrayInputStream;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.text.PDFTextStripper;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.json.JsonMapper;

/**
 * The generic flattening this renderer applies to any report key's own {@code POST /reports/{key}/run} answer
 * (ticket 52, FR-RPT-005) — no report-specific code, so this is exercised against a stand-in shape rather than a
 * real catalogue answer; {@link ReportScheduleIT} exercises it end to end against the real catalogue.
 */
class ScheduledReportRendererTest {

    private static final List<String[]> HEADER = List.of(new String[] {"Report", "visitor-flow"}, new String[] {"Generated by", "Admin"});

    /** The same "rows: List<Map<String, Object>>" shape {@code OperationalReportResponse}/{@code DomainReportPage}
     * already use, with one nested value (the localised-name shape {@code Map<String, String>} a real report row
     * sometimes carries) to exercise the "not a scalar" fallback. */
    private record FakeReport(String key, List<Map<String, Object>> rows, Map<String, Object> totals) {}

    private static Map<String, Object> row(String visitorCode, long count, Map<String, String> service) {
        Map<String, Object> row = new LinkedHashMap<>();
        row.put("visitor_code", visitorCode);
        row.put("ticket_count", count);
        row.put("service", service);
        return row;
    }

    private final ScheduledReportRenderer renderer = new ScheduledReportRenderer(JsonMapper.builder().build());

    @Test
    void csvCarriesTheHeaderBlockColumnHeadersAndRawValues() throws Exception {
        FakeReport report = new FakeReport("visitor-flow", List.of(row("V-1", 3, Map.of("en", "Consultation")), row("V-2", 5, Map.of("en", "Triage"))), Map.of("total", 8));

        ScheduledReportRenderer.Rendered rendered = renderer.render(csv(), HEADER, report);

        assertThat(rendered.rowCount()).isEqualTo(2);
        String csv = new String(rendered.content(), java.nio.charset.StandardCharsets.UTF_8);
        assertThat(csv).contains("\"Report\",\"visitor-flow\"").contains("\"Generated by\",\"Admin\"");
        assertThat(csv).contains("\"visitor_code\"").contains("\"ticket_count\"").contains("\"service\"");
        assertThat(csv).contains("\"V-1\"").contains("\"3\"").contains("\"V-2\"").contains("\"5\"");
        // a nested object cell is rendered as its own compact JSON text, not expanded into more columns
        assertThat(csv).contains("Consultation");
    }

    @Test
    void xlsxOpensWithColumnHeadersAndDataRows() throws Exception {
        FakeReport report = new FakeReport("visitor-flow", List.of(row("V-1", 3, Map.of("en", "Consultation"))), Map.of());

        ScheduledReportRenderer.Rendered rendered = renderer.render(xlsx(), HEADER, report);

        try (var workbook = WorkbookFactory.create(new ByteArrayInputStream(rendered.content()))) {
            var sheet = workbook.getSheetAt(0);
            assertThat(sheet.getRow(0).getCell(0).getStringCellValue()).isEqualTo("Report");
            assertThat(sheet.getRow(0).getCell(1).getStringCellValue()).isEqualTo("visitor-flow");
            Row header = sheet.getRow(3); // two header lines + one blank row
            List<String> headerValues = List.of(header.getCell(0).getStringCellValue(), header.getCell(1).getStringCellValue(), header.getCell(2).getStringCellValue());
            assertThat(headerValues).contains("visitor_code", "ticket_count", "service");
            Row dataRow = sheet.getRow(4);
            assertThat(dataRow.getCell(0).getStringCellValue()).isEqualTo("V-1");
        }
    }

    @Test
    void pdfContainsTheHeaderBlockAndDataRow() throws Exception {
        FakeReport report = new FakeReport("visitor-flow", List.of(row("V-9", 7, Map.of("en", "Triage"))), Map.of());

        ScheduledReportRenderer.Rendered rendered = renderer.render(pdf(), HEADER, report);

        assertThat(rendered.content()).startsWith("%PDF".getBytes(java.nio.charset.StandardCharsets.US_ASCII));
        try (var document = Loader.loadPDF(rendered.content())) {
            String text = new PDFTextStripper().getText(document);
            assertThat(text).contains("Report").contains("visitor-flow").contains("V-9");
        }
    }

    @Test
    void anAnswerWithNoRowsRendersAnEmptyTableRatherThanFailing() throws Exception {
        FakeReport report = new FakeReport("visitor-flow", List.of(), Map.of());

        ScheduledReportRenderer.Rendered rendered = renderer.render(csv(), HEADER, report);

        assertThat(rendered.rowCount()).isZero();
        assertThat(new String(rendered.content(), java.nio.charset.StandardCharsets.UTF_8)).contains("\"Report\",\"visitor-flow\"");
    }

    private static ReportExportFormat csv() {
        return ReportExportFormat.fromWire("csv").orElseThrow();
    }

    private static ReportExportFormat xlsx() {
        return ReportExportFormat.fromWire("xlsx").orElseThrow();
    }

    private static ReportExportFormat pdf() {
        return ReportExportFormat.fromWire("pdf").orElseThrow();
    }
}
